---
title: "STA302_project_part1"
author: "Lu (Lucy) Bai"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

We load in the Ames Housing dataset, form the subset, clean the subset.
```{r}
# Load the original Ames Housing data
AmesHousing = read.csv("/Users/lucybai/Documents/UofT/university academy/Forth year F/STA302/STA302 project/AmesHousing.csv", header=T)
# Subset the data
subset = AmesHousing[,c(20, 41, 50, 52, 55, 57, 61, 72, 80)]
# Clean subset
Housing_data = na.omit(subset)
summary(Housing_data)
```
make transformation
```{r}
Housing_data$transformed_price = log(Housing_data$Sale_Price)
summary(Housing_data)
```


Fit the model
```{r}
fit = lm(transformed_price ~ Year_Built + Full_Bath + Bedroom_AbvGr 
         + TotRms_AbvGrd + Garage_Cars + Pool_QC + Heating_QC, 
         data = Housing_data)
summary(fit)
```



Plot each variable against each other.
```{r}
plot(Housing_data[, c(1, 3, 4, 5, 6, 7, 10)], col="cadetblue")
```


y vs. y^
```{r}
sale_price = Housing_data$transformed_price
fitted_values = fitted(fit)
plot(fitted_values, sale_price,
     main = "log(Sale price) versus regression fit",
     xlab = "Fitted values", ylab = "log(Sale Price) (USD)")
abline(0, 1, 
       col=c("blue"), lty=1)
legend("bottomright", legend=c("y = x line"),
       col=c("blue"), lty=1)
```

e^ vs. x
```{r}
par(mfrow=c(2,2))

residual_values = resid(fit)

plot(residual_values ~ Housing_data$Year_Built, 
     main="Residuals versus Year Built",
     xlab="Year Built", ylab="Residuals")
abline(h=0, col="red", lwd=3, lty=3)

plot(residual_values ~ Housing_data$Full_Bath, 
     main="Residuals versus Full Bath",
     xlab="Full Bath", ylab="Residuals")
abline(h=0, col="red", lwd=3, lty=3)

plot(residual_values ~ Housing_data$Bedroom_AbvGr, 
     main="Residuals versus Bedrooms",
     xlab="Bedrooms Above the Ground", ylab="Residuals")
abline(h=0, col="red", lwd=3, lty=3)

plot(residual_values ~ Housing_data$TotRms_AbvGrd, 
     main="Residuals versus Total Rooms",
     xlab="Total Rooms Above ground", ylab="Residuals")
abline(h=0, col="red", lwd=3, lty=3)

plot(residual_values ~ Housing_data$Fireplaces, 
     main="Residuals versus Fireplaces",
     xlab="Number of Fireplaces", ylab="Residuals")
abline(h=0, col="red", lwd=3, lty=3)

plot(residual_values ~ Housing_data$Garage_Cars, 
     main="Residuals versus Garage Car Capacity",
     xlab="Size of Garage in Capacity", ylab="Residuals")
abline(h=0, col="red", lwd=3, lty=3)

```


```{r}
plot(fit, which = 1)
```

```{r}
sresidual_values = rstandard(fit)
par(mfrow=c(1,2))
hist(sresidual_values,
     main = "Standardized residuals histogram",
     xlab = "Standardized residuals")
plot(fit, which = 2)
```

